### ISSUE TITLE
Type-clustered layouts

### ISSUE THREAD

**Issue by longbinlai** [GraphScope/portal#427]
A new layout to plot the whole graph can be arranged by clustering per-type of vertices, like: 
![C13201A0-E547-4300-8AA1-BE0D75553155](https://github.com/user-attachments/assets/93f4a1c4-180a-4a7b-8a12-34b0944f1b78)

**Comment by pomelo-nwu** [comment]
- fixed：https://github.com/GraphScope/portal/pull/455
