### ISSUE TITLE
Query page should automatically scroll to the top while clicking the stored procedure 

### ISSUE THREAD

**Issue by longbinlai** [GraphScope/portal#436]
Now when clicking the stored procedure, it is already running, but the query page is still in the current position rather than scrolling to the top where the clicked stored procedure is running. 

![Screenshot 2024-07-17 at 15 36 31](https://github.com/user-attachments/assets/ecd85094-ec87-4fed-90e7-3bb474389800)

**Comment by totoago** [comment]
https://github.com/GraphScope/portal/pull/440
