### ISSUE TITLE
The vertex/edge's information shown only after hovering

### ISSUE THREAD

**Issue by longbinlai** [GraphScope/portal#439]
Now the information (id) is shown on every vertex by default. 
When there are many vertices in the plotting area, it looks a bit messy. 
Can we do showing these info after hovering over certain vertices/edges??

![Screenshot 2024-07-18 at 14 20 57](https://github.com/user-attachments/assets/58dc527b-c976-4235-a406-1b889e37932a)

**Comment by pomelo-nwu** [comment]
- fixed: https://github.com/GraphScope/portal/pull/456
