### ISSUE TITLE
bug: the list of stored procedures is not fully shown

### ISSUE THREAD

**Issue by longbinlai** [GraphScope/portal#444]
Open http://gsp.blue/querying?name=graph_algo&graph_id=1&tab=store-procedure,
Scroll down to the bottom of the page:
![lQLPJwgwO80zWgfMjs0CK7AQoVbj4pZMAAaEJQtia6UA_555_142](https://github.com/user-attachments/assets/5b9f2e28-d35c-4d88-8b04-d9dbe0832f0d)

**Comment by totoago** [comment]
https://github.com/GraphScope/portal/pull/460
