### ISSUE TITLE
Portal will shut down if the nodes of an edge are not returned by Cyphter query

### ISSUE THREAD

**Issue by longbinlai** [GraphScope/portal#498]
An example of the query is:

```
Match (n)-[e1]->(r:Paper), (r)-[e2]->(task:Task) where n.title starts with "GraphScope" return n, r, e1, e2
```

where task is not returned by accident. 

This will cause crashing portal.

**Comment by pomelo-nwu** [comment]
![image](https://github.com/user-attachments/assets/83f70489-d8b4-42ff-9a07-ac4b5564d6ee)
![image](https://github.com/user-attachments/assets/a1c7c6c5-4fdb-459b-9b32-bdaccb2716ab)
