### ISSUE TITLE
[Bug] With README QuickStart WebUI 404 

### ISSUE THREAD

**Issue by JackyYangPassion** [GraphScope/portal#545]
# QuickStart
```
docker run -it \
--name my-portal \
-p 8888:8888 \
-e COORDINATOR=http://host.docker.internal:8080 \
ghcr.io/graphscope/portal:latest
```

# Screenshot

![image](https://github.com/user-attachments/assets/37a30541-c4b7-483b-af6b-f51972989a61)

**Comment by pomelo-nwu** [comment]
@JackyYangPassion Have you started the GraphScope interactive Docker? The `COORDINATOR` in the script is the endpoint of interactive
